package webadmin

import (
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"gravinet/internal/config"
)

// Applying router advertisements: write the daemon's config, then reload it.
// Mirrors the FRR integration's shape — gravinet owns the file and
// regenerates it whole, never edits in place — with one difference that
// matters for safety.
//
// gravinet refuses to overwrite an radvd.conf it did not write. A host may
// already be advertising from a hand-maintained file, and silently replacing
// it would take down a working LAN the moment someone enabled this feature to
// try it out. The marker on the first line is what distinguishes the two, and
// an unmarked file is reported back rather than clobbered.
const radvdMarker = "# Generated by gravinet."

// radvdOwned reports whether the file at path is gravinet's to rewrite:
// either absent, or carrying the marker. An unreadable file is treated as not
// ours, which fails safe.
func radvdOwned(path string) bool {
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return true
	}
	if err != nil {
		return false
	}
	return strings.HasPrefix(string(b), radvdMarker)
}

// applyRouterAdvert writes radvd.conf and reloads the daemon. Returns an
// operator-facing note describing what actually happened, since "applied" has
// several shades here — no daemon installed, nothing enabled, or a file that
// isn't ours — and each needs saying rather than reporting a bare success.
func applyRouterAdvert(c config.RAConfig) (note string, err error) {
	installed := ""
	if !radvdInstalled() {
		// Enabling the feature is the operator asking for advertisements;
		// making them go and install a package by hand first is a worse
		// answer than doing it for them. Reported in the note either way, so
		// a package appearing on the host is never silent.
		if err := installRadvd(); err != nil {
			return "configuration saved, but no router-advertisement daemon is available: " + err.Error(), nil
		}
		installed = "installed radvd; "
	}
	// A file gravinet did not write is set aside, not refused and not
	// destroyed. Refusing meant an operator who enabled the feature got a
	// dead page and an instruction to go and move a file by hand, which is
	// not a real answer; overwriting silently would lose a hand-maintained
	// config. Renaming does neither: advertisements start now, and whatever
	// was there is still on disk to consult or restore.
	backedUp := ""
	if !radvdOwned(radvdConfPath) {
		to, err := setAsideRadvdConf(radvdConfPath)
		if err != nil {
			return "", fmt.Errorf("could not set aside the existing %s: %w", radvdConfPath, err)
		}
		backedUp = "kept the previous config at " + to + "; "
	}

	ifaces := c.EnabledInterfaces()
	if len(ifaces) == 0 {
		// Nothing to advertise. Stop the daemon rather than leaving it
		// running on a stale file: disabling the feature has to actually
		// stop the advertisements, or the off switch is decorative.
		if err := os.WriteFile(radvdConfPath, []byte(radvdMarker+"\n# No interfaces configured.\n"), 0o644); err != nil {
			return "", fmt.Errorf("write %s: %w", radvdConfPath, err)
		}
		raService("stop")
		return installed + backedUp + "router advertisements stopped (no interfaces enabled)", nil
	}

	conf := renderRadvd(c)
	if !strings.Contains(conf, "interface ") {
		// Every entry resolved to no prefixes. radvd would refuse to start on
		// this, so say why instead of leaving a daemon crash-looping.
		return "", fmt.Errorf("no interface resolved to an advertisable /64 — name a prefix explicitly, or configure a global IPv6 address on the interface")
	}
	if err := os.WriteFile(radvdConfPath, []byte(conf), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", radvdConfPath, err)
	}
	if !raService("restart") {
		return "", fmt.Errorf("wrote %s but the radvd service would not start — check `journalctl -u radvd` (or the rtadvd log on FreeBSD)", radvdConfPath)
	}
	raService("enable")
	return fmt.Sprintf("%s%sadvertising on %d interface(s)", installed, backedUp, len(ifaces)), nil
}

// handleRouterAdvert serves the RA editor: GET returns the stored config plus
// whether a daemon is present; POST mutates it and applies.
func (s *Server) handleRouterAdvert(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		cfg, err := config.Load(s.configPath)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{"error": err.Error()})
			return
		}
		// mesh_ifaces are this node's own overlay devices. The picker filters
		// them out: advertising on one would tell mesh peers this node is
		// their router, which is never what an operator means here and is not
		// something a hint alone should be relied on to prevent. Sent as data
		// rather than filtered server-side into the interface list, because
		// the picker's list comes from the shared /api/interfaces cache and
		// the exclusion belongs to this page.
		var meshIfaces []string
		for _, i := range s.be.Interfaces() {
			if i.Iface != "" {
				meshIfaces = append(meshIfaces, i.Iface)
			}
		}
		writeJSON(w, http.StatusOK, map[string]any{
			"ra":          cfg.RouterAdvert,
			"installed":   radvdInstalled(),
			"owned":       radvdOwned(radvdConfPath),
			"mesh_ifaces": meshIfaces,
		})
		return
	}

	var req struct {
		Op, Iface       string
		Prefixes        []string
		DNS             []string
		Search          []string
		Preference      string `json:"preference"`
		Managed         bool   `json:"managed"`
		OtherConfig     bool   `json:"other_config"`
		DefaultLifetime int    `json:"default_lifetime"`
		NotDefault      bool   `json:"not_default"`
		Enabled         bool   `json:"enabled"`
		Index           int
	}
	if !decode(w, r, &req) {
		return
	}

	var note string
	err := s.mutateConfig(r, func(cfg *config.Config) error {
		ra := &cfg.RouterAdvert
		switch req.Op {
		case "feature":
			ra.Enabled = req.Enabled
		case "add", "update":
			e := config.RAInterface{
				Iface:    strings.TrimSpace(req.Iface),
				Prefixes: trimAll(req.Prefixes), DNS: trimAll(req.DNS), Search: trimAll(req.Search),
				Preference: strings.ToLower(strings.TrimSpace(req.Preference)),
				Managed:    req.Managed, OtherConfig: req.OtherConfig,
				DefaultLifetime: req.DefaultLifetime, NotDefault: req.NotDefault,
			}
			if err := e.Validate(); err != nil {
				return err
			}
			// The picker hides mesh devices, but a picker is a convenience,
			// not a control: this is what actually prevents it. Advertising
			// into the overlay would tell every mesh peer this node is their
			// router.
			if err := s.refuseMeshIface(e.Iface); err != nil {
				return err
			}
			if req.Op == "add" {
				for _, x := range ra.Interfaces {
					if strings.EqualFold(x.Iface, e.Iface) {
						return fmt.Errorf("interface %s is already configured", e.Iface)
					}
				}
				ra.Interfaces = append(ra.Interfaces, e)
				ra.Enabled = true // adding the first interface turns the feature on
			} else {
				if req.Index < 0 || req.Index >= len(ra.Interfaces) {
					return fmt.Errorf("no interface at index %d", req.Index)
				}
				cur := ra.Interfaces[req.Index]
				e.Disabled = cur.Disabled // preserve state
				// The M/O flags and the router lifetime have no controls in
				// the editor, so an update carries none and would otherwise
				// clear whatever is stored. They remain settable by editing
				// the config file, and a UI save must not silently undo that:
				// an operator editing a DNS server should not find their
				// DHCPv6 flag switched off as a side effect.
				e.Managed, e.OtherConfig = cur.Managed, cur.OtherConfig
				e.DefaultLifetime, e.NotDefault = cur.DefaultLifetime, cur.NotDefault
				ra.Interfaces[req.Index] = e
			}
		case "delete", "remove":
			if req.Index < 0 || req.Index >= len(ra.Interfaces) {
				return fmt.Errorf("no interface at index %d", req.Index)
			}
			ra.Interfaces = append(ra.Interfaces[:req.Index], ra.Interfaces[req.Index+1:]...)
		case "enable", "disable":
			if req.Index < 0 || req.Index >= len(ra.Interfaces) {
				return fmt.Errorf("no interface at index %d", req.Index)
			}
			ra.Interfaces[req.Index].Disabled = req.Op == "disable"
		default:
			return fmt.Errorf("unknown op %q", req.Op)
		}
		return nil
	})
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": err.Error()})
		return
	}

	// Apply from the saved config, so what runs is what was stored rather
	// than what was requested.
	if cfg, lerr := config.Load(s.configPath); lerr == nil {
		if n, aerr := applyRouterAdvert(cfg.RouterAdvert); aerr != nil {
			writeJSON(w, http.StatusOK, map[string]any{"ok": true, "restart": false, "note": "saved, but: " + aerr.Error()})
			return
		} else {
			note = n
		}
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "restart": false, "note": note})
}

// setAsideRadvdConf renames an existing radvd.conf out of the way and returns
// where it went. The first displacement lands on a predictable name so an
// operator can find it without guessing; if that name is taken — a second
// hand-written file after a previous takeover — a timestamp is appended
// rather than overwriting the earlier backup, since the whole point is that
// nothing an operator wrote gets destroyed.
func setAsideRadvdConf(path string) (string, error) {
	to := path + ".pre-gravinet"
	if _, err := os.Stat(to); err == nil {
		to = fmt.Sprintf("%s.pre-gravinet.%d", path, time.Now().Unix())
	}
	if err := os.Rename(path, to); err != nil {
		return "", err
	}
	return to, nil
}

// refuseMeshIface rejects one of this node's own overlay devices.
func (s *Server) refuseMeshIface(name string) error {
	for _, i := range s.be.Interfaces() {
		if i.Iface != "" && strings.EqualFold(i.Iface, name) {
			return fmt.Errorf("%s is this node's mesh device for network %q — router advertisements belong on a LAN interface, not the overlay", name, i.Name)
		}
	}
	return nil
}

func trimAll(in []string) []string {
	var out []string
	for _, s := range in {
		if s = strings.TrimSpace(s); s != "" {
			out = append(out, s)
		}
	}
	return out
}
