package webadmin

import (
	"context"
	"fmt"
	"net"
	"net/netip"
	"os/exec"
	"runtime"
	"sort"
	"strings"
	"time"

	"gravinet/internal/config"
)

// IPv6 router advertisements. gravinet renders the daemon's config and
// reloads it, the same shape as the FRR integration next door: gravinet owns
// the file, regenerates it whole from its own config on every apply, and
// never edits in place.
//
// Two daemons, one config model. Linux runs radvd; FreeBSD runs rtadvd, whose
// config format is different enough to need its own renderer rather than a
// flag (see radvdRenderRtadvd). What they share is the semantics, which is
// what config.RAConfig describes.
//
// Scope is deliberately "advertise a directly-attached prefix, plus DNS":
// see config.RAConfig's own doc comment for why mesh-learned prefixes are
// not republished here.

const radvdConfPath = "/etc/radvd.conf"

// ifaceGlobalV6 returns the global IPv6 /64s configured on an interface, used
// when an RA entry names no explicit prefix. Resolved at render time rather
// than stored, so an address change on the interface is picked up by the next
// apply instead of leaving a stale prefix being advertised to hosts that will
// cache it.
func ifaceGlobalV6(name string) []netip.Prefix {
	ifi, err := net.InterfaceByName(name)
	if err != nil {
		return nil
	}
	addrs, err := ifi.Addrs()
	if err != nil {
		return nil
	}
	var out []netip.Prefix
	for _, a := range addrs {
		ipn, ok := a.(*net.IPNet)
		if !ok {
			continue
		}
		addr, ok := netip.AddrFromSlice(ipn.IP)
		if !ok || !addr.Is6() || addr.Is4In6() {
			continue
		}
		// Link-local and loopback are never advertised: a host cannot
		// autoconfigure a routable address from fe80::/10, and offering one
		// would produce addresses that work nowhere.
		if addr.IsLinkLocalUnicast() || addr.IsLoopback() {
			continue
		}
		ones, _ := ipn.Mask.Size()
		if ones != 64 {
			continue // not autoconfigurable; see RAInterface.Validate
		}
		out = append(out, netip.PrefixFrom(addr, ones).Masked())
	}
	sort.Slice(out, func(i, j int) bool { return out[i].String() < out[j].String() })
	return out
}

// radvdPrefixes resolves an entry's advertised prefixes: what the operator
// listed, or the interface's own global /64s when they listed none.
func radvdPrefixes(e config.RAInterface) []netip.Prefix {
	if len(e.Prefixes) == 0 {
		return ifaceGlobalV6(e.Iface)
	}
	var out []netip.Prefix
	for _, p := range e.Prefixes {
		if pfx, err := netip.ParsePrefix(strings.TrimSpace(p)); err == nil && pfx.Addr().Is6() {
			out = append(out, pfx.Masked())
		}
	}
	return out
}

// renderRadvd renders /etc/radvd.conf. Pure: no I/O beyond the interface
// address lookup for entries that named no prefix, so it is testable without
// a daemon.
//
// An entry that resolves to no prefixes is skipped entirely rather than
// emitted as an empty interface block. radvd refuses to start on an interface
// stanza with no prefix, and one misconfigured LAN taking down the
// advertisements for every other LAN is a far worse failure than that one LAN
// going unadvertised.
func renderRadvd(c config.RAConfig) string {
	var b strings.Builder
	b.WriteString("# Generated by gravinet. Edits will be overwritten.\n")
	for _, e := range c.EnabledInterfaces() {
		pfxs := radvdPrefixes(e)
		if len(pfxs) == 0 {
			continue
		}
		if !safeToken(e.Iface) {
			continue
		}
		fmt.Fprintf(&b, "\ninterface %s\n{\n", e.Iface)
		b.WriteString("\tAdvSendAdvert on;\n")
		fmt.Fprintf(&b, "\tAdvManagedFlag %s;\n", radvdOnOff(e.Managed))
		fmt.Fprintf(&b, "\tAdvOtherConfigFlag %s;\n", radvdOnOff(e.OtherConfig))
		switch {
		case e.NotDefault:
			// Advertise the prefix but explicitly not this node as a router.
			b.WriteString("\tAdvDefaultLifetime 0;\n")
		case e.DefaultLifetime > 0:
			fmt.Fprintf(&b, "\tAdvDefaultLifetime %d;\n", e.DefaultLifetime)
		}
		for _, p := range pfxs {
			fmt.Fprintf(&b, "\n\tprefix %s\n\t{\n\t\tAdvOnLink on;\n\t\tAdvAutonomous %s;\n\t\tAdvRouterAddr on;\n\t};\n",
				p, radvdOnOff(!e.Managed))
		}
		if dns := radvdCleanDNS(e.DNS); len(dns) > 0 {
			fmt.Fprintf(&b, "\n\tRDNSS %s\n\t{\n\t};\n", strings.Join(dns, " "))
		}
		if s := radvdCleanSearch(e.Search); len(s) > 0 {
			fmt.Fprintf(&b, "\n\tDNSSL %s\n\t{\n\t};\n", strings.Join(s, " "))
		}
		b.WriteString("};\n")
	}
	return b.String()
}

func radvdOnOff(v bool) string {
	if v {
		return "on"
	}
	return "off"
}

// radvdCleanDNS keeps only valid IPv6 addresses. RDNSS has no representation
// for an IPv4 server, and radvd rejects the whole file rather than the one
// line if given something else.
func radvdCleanDNS(in []string) []string {
	var out []string
	for _, d := range in {
		if a, err := netip.ParseAddr(strings.TrimSpace(d)); err == nil && a.Is6() && !a.Is4In6() {
			out = append(out, a.String())
		}
	}
	return out
}

// radvdCleanSearch drops anything that could break out of the DNSSL line.
func radvdCleanSearch(in []string) []string {
	var out []string
	for _, d := range in {
		d = strings.TrimSpace(d)
		if d != "" && safeToken(d) {
			out = append(out, d)
		}
	}
	return out
}

// radvdInstalled reports whether a router-advertisement daemon is present.
func radvdInstalled() bool {
	for _, bin := range []string{"radvd", "rtadvd"} {
		if _, err := exec.LookPath(bin); err == nil {
			return true
		}
	}
	return false
}

// installRadvd installs the daemon through pkgman, the package-manager wrapper
// gravinet already ships and installs alongside its own binary, so this works
// the same way across apt/dnf/pacman/pkg rather than growing a per-distro
// branch here.
//
// Only ever called from an explicit apply — enabling the feature is the
// operator asking for advertisements, and refusing to work until they go and
// install a package by hand is a worse answer than doing it. It is never
// called from a GET or from any background reconciler, because installing a
// package is not something that should happen as a side effect of opening a
// page.
//
// FreeBSD is deliberately excluded: its daemon is rtadvd, gravinet does not
// yet render rtadvd's config format, and installing a daemon that would then
// be pointed at a file it cannot parse is worse than not installing it.
func installRadvd() error {
	if runtime.GOOS == "freebsd" {
		return fmt.Errorf("rtadvd config rendering is not implemented yet, so gravinet will not install it")
	}
	bin, err := exec.LookPath("pkgman")
	if err != nil {
		return fmt.Errorf("pkgman not found; install radvd with your package manager")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	out, err := exec.CommandContext(ctx, bin, "install", "radvd").CombinedOutput()
	if err != nil {
		return fmt.Errorf("installing radvd: %v (%s)", err, strings.TrimSpace(lastLine(string(out))))
	}
	if !radvdInstalled() {
		return fmt.Errorf("pkgman reported success but no radvd binary is on PATH")
	}
	return nil
}

// lastLine returns the final non-empty line of command output — enough to
// carry a package manager's actual complaint into an error without pasting a
// screenful of progress into the UI.
func lastLine(s string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	for i := len(lines) - 1; i >= 0; i-- {
		if t := strings.TrimSpace(lines[i]); t != "" {
			return t
		}
	}
	return ""
}

// ipv6RASupported gates the Traffic > IPv6 RA nav item and section, the same
// way bgpSupported() gates Traffic > BGP: absent the daemon there is nothing
// the page can do, so the entry is hidden rather than left dead.
//
// Two conditions, and the platform one is not a proxy for the other. gravinet
// renders radvd's config format only; FreeBSD's daemon is rtadvd and its
// format differs, so a FreeBSD host can have a perfectly good rtadvd
// installed and still not be servable here. Hiding on GOOS is what keeps that
// host from being offered a page that would write it a file it cannot parse.
//
// Note this makes installRadvd a repair path rather than a first-run one: an
// operator cannot reach the page to trigger an install while the daemon is
// missing. It still earns its place — a daemon removed by a later package
// operation is reinstalled on the next apply instead of failing — but the
// first install is now the operator's to do, and that trade is deliberate.
func ipv6RASupported() bool {
	if runtime.GOOS != "linux" {
		return false
	}
	return radvdInstalled()
}
